services:
  app:
    image: mcr.microsoft.com/devcontainers/base:jammy
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportsday
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
